### ISSUE TITLE
Serve handler for vercel/node serverless functions

### ISSUE THREAD

**Issue by cohlar** [inngest/inngest#553]
### Discussed in https://github.com/orgs/inngest/discussions/552

Add `serve` handler for vercel/node serverless functions (in addition to currently supported vercel express and nextjs handlers).

<div type='discussions-op-text'>

<sup>Originally posted by **cohlar** August  4, 2023</sup>
Hi,

I'm trying to setup inngest with Vercel serverless functions, Vite and Vue. I haven't been able to make it work yet, and I was hoping I could get some help 😃

So far what I did in [this repo](https://github.com/cohlar/vercel-vite-vue):
✅ Created a new Vue project based on Vite with `npm create vue@latest`
✅ Created a serverless function named "serverless-example" based on the [Vercel quickstart guide](https://vercel.com/docs/concepts/functions/serverless-functions/quickstart#create-a-serverless-function)
✅ Deployed to Vercel - [see app](https://vercel-vite-vue-dev-brandfolio.vercel.app/) and [invoke serverless-example function](https://vercel-vite-vue-dev-brandfolio.vercel.app/api/serverless-example?query=123)
✅ Added [Inngest's official Vercel integration](https://vercel.com/integrations/inngest) to the Vercel project
❌ Followed the [Inngest quick start guide](https://www.inngest.com/docs/quick-start) with a [custom serve handler](https://github.com/inngest/inngest-js/blob/main/src/examples/handler.ts) (which I haven't really customized) and re-deployed with Vercel. Invocations fail - [see for yourself](https://vercel-vite-vue-dev-brandfolio.vercel.app/api/inngest)

<details>
<summary>Here is the error from the Vercel logs when invoking `/api/inngest`:</summary>

```
Unhandled Promise Rejection 	{"errorType":"Runtime.UnhandledPromiseRejection","errorMessage":"TypeError: req.headers.get is not a function","reason":{"errorType":"TypeError","errorMessage":"req.headers.get is not a function","stack":["TypeError: req.headers.get is not a function","    at InngestCommHandler.inngest_1.InngestCommHandler.body.body [as handler] (/vercel/path0/api/inngest/serve.ts:78:59)","    at /var/task/node_modules/inngest/components/InngestCommHandler.js:264:71","    at ServerTiming.wrap (/var/task/node_modules/inngest/helpers/ServerTiming.js:69:43)","    at Object.handler (/var/task/node_modules/inngest/components/InngestCommHandler.js:264:44)","    at handler (/var/task/___vc/__launcher.js:53:33)","    at /var/task/___vc/helpers-CC7Q2OBA.js:454:20","    at AsyncLocalStorage.run (node:async_hooks:338:14)","    at Server.<anonymous> (/var/task/___vc/__launcher.js:82:28)","    at Server.emit (node:events:513:28)","    at parserOnIncoming (node:_http_server:1091:12)"]},"promise":{},"stack":["Runtime.UnhandledPromiseRejection: TypeError: req.headers.get is not a function","    at process.<anonymous> (file:///var/runtime/index.mjs:1186:17)","    at process.emit (node:events:525:35)","    at process.emit (/var/task/___vc/__sourcemap_support.js:602:21)","    at emit (node:internal/process/promises:149:20)","    at processPromiseRejections (node:internal/process/promises:283:27)","    at processTicksAndRejections (node:internal/process/task_queues:96:32)"]}
Unknown application error occurred
Runtime.Unknown
```
</details>

1. Do I have to use an Express server to serve my Vercel serverless functions with Inngest?
2. And if not, what am I missing to make it work? e.g. do I need to adjust my custom `serve` handler?
3. When I deploy with Vercel, I do not see any function in the Inngest dashboard. Will fixing the `serve` handler fix this, or is this a separate issue?

In regards to 1., adding an Express server feels redundant / overkill to me - as [mentioned by Vercel](https://vercel.com/guides/using-express-with-vercel):
> When we deploy a server (Express.js based application) within a Serverless Function, we are executing a full server implementation on each request. This is an anti-pattern, as Serverless Functions should serve one purpose.

Thanks for your help!</div>

**Comment by cohlar** [comment]
Well I have tried to push a branch and create a PR, but it looks like I would need permissions. So I'll just share my handler here, in case anybody's interested.

```ts
import {
  headerKeys,
  InngestCommHandler,
  queryKeys,
  type ServeHandler,
} from "inngest";
import { type VercelRequest, type VercelResponse } from "@vercel/node";
import { type SupportedFrameworkName } from "./types";

export const name: SupportedFrameworkName = "vercel/node";

export const serve: ServeHandler = (nameOrInngest, fns, opts) => {
  const handler = new InngestCommHandler(
    name,
    nameOrInngest,
    fns,
    opts,
    (request: VercelRequest, _response: VercelResponse) => {
      const url = new URL(
        request.url || "",
        `https://${request.headers.host || ""}`
      );
      return {
        url,
        register: () => {
          if (request.method === "PUT") {
            return {
              deployId: url.searchParams.get(queryKeys.DeployId) as string,
            };
          }
        },
        run: () => {
          if (request.method === "POST") {
            return {
              data: request.body as Record<string, unknown>,
              fnId: url.searchParams.get(queryKeys.FnId) as string,
              stepId: url.searchParams.get(queryKeys.StepId) as string,
              signature: request.headers[headerKeys.Signature] as string,
            };
          }
        },
        view: () => {
          if (request.method === "GET") {
            return {
              isIntrospection: url.searchParams.has(queryKeys.Introspect),
            };
          }
        },
      };
    },
    ({ body, status, headers }, request, response): void => {
      Object.entries(headers).forEach(([name, value]) => {
        response.setHeader(name, value);
      });

      response.status(status).json({
        body,
        query: request.query,
        cookies: request.cookies,
      });
    }
  );

  return handler.createHandler();
};
```

Of course you'd need to run `yarn add -D @vercel/node` and add "vercel/node" to `type SupportedFrameworkName`.

**Comment by cohlar** [comment]
The above code failed to run steps. The open PR has the updated code that works with function steps.
